package com.ai.drools.insert
import com.ai.study.drools.Customer;
import com.ai.study.drools.Order;

rule "insert"
    salience 185
    //lock-on-active true
    no-loop true
    when
    	//eval(true)
        $customer:Customer(name =="张三");
    then
    	System.out.println("===========");
        Customer cus=new Customer();
		cus.setName("张三");
		cus.setAge(1);
		insert(cus);
end


rule "insert_rhs"
    salience 196
    //lock-on-active true
   // no-loop true
    when
       $customer:Customer(name =="张三");
    then
         //modify($customer){
		 //	setName("张三"),
	     //	setAge(5)
		//}
        System.out.println("insert_rhs----"+$customer.getAge());
end
