package com.ai.drools.insert
import com.ai.study.drools.Customer;
import com.ai.study.drools.Order;

query "testQuery"
	customer:Customer(age>4)
end

query "testQuery_params"(int $age)
	customer:Customer(age>$age)
end

rule "insert"
    salience 199
  //  no-loop true
    //lock-on-active true
    when
       eval(true)
    then
    	System.out.println("===========");
        Customer cus=new Customer();
		cus.setName("张三");
		cus.setAge(5);
		insert(cus);
end


rule "insert_rhs"
     salience 196
    //lock-on-active true
   // no-loop true
    when
       $customer:Customer(name =="张三");
    then
    	Customer cus=new Customer();
		cus.setName("张三");
		cus.setAge(8);
		insert(cus);
end

   
