package com.ai

import com.ai.study.integral.IntegralBean;

rule subBackNumsPoint
	// 发生退货，扣减10分
	salience 10
	lock-on-active true
	when
		$integralBean : IntegralBean(backNums >= 1)
	then
		$integralBean.setPoint($integralBean.getPoint()-30);
		$integralBean.recordPointLog($integralBean.getUserName(),"subBackNumsPoint",$integralBean.getPoint());
end

rule subBackMondyPoint
	// 退货金额大于100，扣减100分
	salience 9
	lock-on-active true
	when
		$integralBean : IntegralBean(backMondy >= 100)
	then
		$integralBean.setPoint($integralBean.getPoint()-10);
		$integralBean.recordPointLog($integralBean.getUserName(),"subBackMondyPoint",$integralBean.getPoint());
end